### ISSUE TITLE
[1.3.1 AE] CTD on load or new game start

### ISSUE THREAD

**Issue by Idrinth** [cppcooper/MagickaReserve#1]
Would be happy about any hint at what I could change to fix it.

[crash-2023-08-29-14-47-22.log](https://github.com/cppcooper/MagickaReserve/files/12466378/crash-2023-08-29-14-47-22.log)
[ReservedMagicka.log](https://github.com/cppcooper/MagickaReserve/files/12466405/ReservedMagicka.log)

**Comment by cppcooper** [comment]
Weird. That log points to https://github.com/cppcooper/MagickaReserve/blob/249b3a681c19ce4356137a56e650150825eda2ca/src/EquipEventSink.cpp#L25-L28
Specifically line 27, implying `rpel` is null. Which it definitely should not be.

You are probably missing the esl, or it's disabled or something like that. If the esl was loading properly, it should make the global variables available. In turn meaning the dll should be able to find/load them. 

Unless it's AE but not 1.6.640 in which case I guess it could be an SKSE or commonlib problem. I hope this is helpful to you, cause I don't think I can resolve this for you if it's a problem other than the esl missing

**Comment by Idrinth** [comment]
my bad, the esl seems to have been disabled - sorry about wasting your time.

**Comment by cppcooper** [comment]
Don't worry about it. Happy I could help. Good luck with your 120GB of RAM XD
